### ISSUE TITLE
After hotwire install are you able to freely use Stimulus like normal?

### ISSUE THREAD

**Issue by cgibsonmm** [hotwired/hotwire-rails#11]
After installing Hotwire I am attempting to build a new stimulus controller but any import of an external package causes the Failed to autoload error, with no other error reporting. Are there other steps that can be taken to get this up and running?

**Comment by dhh** [comment]
You need to either import from a CDN ala Skypack and reference the full URL, or you need to download your dependency and stick it in app/assets/javascripts/libraries/mylib@1.0.js and reference as "mylib".
