### ISSUE TITLE
Redirect with anchor is not handled correctly

### ISSUE THREAD

**Issue by SimonBo** [hotwired/hotwire-rails#15]
I tried redirecting to a path with anchor specified (`redirect_to root_path, anchor: 'anchor')`) during turbo stream response but it always goes to the top of the page (as if anchor was not specified). Is there a way to make TURBO_STREAM redirect handle anchors? I noticed that using anchors works correctly with links thou.

**Comment by dhh** [comment]
Believe this is fixed now on Turbo. If not, address on turbo repo with a reproducible case.
