### ISSUE TITLE
Should stimulus-rails be an optional depenency?

### ISSUE THREAD

**Issue by jcoyne** [hotwired/hotwire-rails#17]
If a developer wants to use hotwire-rails for webpacker, it also includes stimulus-rails as a dependency.  However stimulus-rails says:

> If you want to use Stimulus with a bundler, you should use Webpacker instead. This gem is purely intended for those who wish to use Stimulus with the asset pipeline using ESM in the browser.

**Comment by dhh** [comment]
You can just use turbo-rails directly 👍
