### ISSUE TITLE
Stimulus controller not working after upgrading to hotwire-rails 0.1.3

### ISSUE THREAD

**Issue by leonardoprg** [hotwired/hotwire-rails#19]
Hey guys,

Im having an issue after upgrading hotwire-rails to `0.1.3` version.

Before all worked as expected, but after upgrading, the pages that are handled by turbo does not works stimulus controller correctly.
example:

```
# site/index.html
<div data-controller="site-index"></div>
```

```
# site_index_controller.js
export default class extends Controller {
   connect() {
      alert(1);
   }
}
```

when I open directly the site/index (without using a link) it works as expected and show up the alert.
but when I open another page and use a link to goes to site/index, it does not loads the controller (and does not show up the alert)
no error on console log.

any idea what is happening?

Thanks

**Comment by seanpdoyle** [comment]
A recent change to the [hotwired/stimulus-rails](https://github.com/hotwired/stimulus-rails/commit/981da83611f594481d22e19bf8419941550ebde2) changed how controller autoloading functioned. It's part of the [v0.2.1](https://github.com/hotwired/stimulus-rails/releases/tag/v0.2.1) release. Could you upgrade the `stimulus-rails` gem to that version then try to reproduce?

**Comment by seanpdoyle** [comment]
I'd imagine the plan it to keep hotwire-rails, stimulus-rails, and turbo-rails in lock-step once everything settles.

In these early pre-1.0 stages, I think each pillar might move more independently.

**Comment by leonardoprg** [comment]
I have tried here, and seems to not working yet

my Gemfile:

```
gem 'hotwire-rails', '0.1.3'
gem 'stimulus-rails', '0.2.1'
```

my controller is mentioned above and I still having the same issue.
any other idea?

**Comment by seanpdoyle** [comment]
@leonardoprg I've opened https://github.com/hotwired/stimulus-rails/pull/30 to try and reproduce the behavior you've described, but the test suite passes. Could you provide feedback on that branch to help me reproduce what you're experiencing?
