### ISSUE TITLE
Detect if app is using Webpacker, then skip stimulus:install

### ISSUE THREAD

**Issue by dhh** [hotwired/hotwire-rails#2]
hotwire-rails installs stimulus-rails, which was designed exclusively for use with the asset pipeline. It doesn't make sense to run stimulus:install, if the app is using Webpacker. So detect and skip that.

(This essentially means that if you're not using the asset pipeline, you can just use the turbo-rails gem directly. But I could see people following tutorials and missing this part.)

**Comment by dhh** [comment]
Actually, even better, we should upgrade stimulus-rails to have a stimulus:install task that adds stimulus to package.json if it isn't already. Ala webpack:install:stimulus. Going to do that instead.

**Comment by mjgiarlo** [comment]
@dhh :speech_balloon: 
> Actually, even better, we should upgrade stimulus-rails to have a stimulus:install task that adds stimulus to package.json if it isn't already. Ala webpack:install:stimulus. Going to do that instead.

Is there an issue I might subscribe to for tracking this? Thanks for your work on this.

**Comment by thelucid** [comment]
Just hit a `Error: Cannot find module 'controllers'` error when using the `hotwire-rails` gem on a default Rails app. Does that mean we should bypass `hotwire-rails` in this case?

**Comment by thelucid** [comment]
As a follow up, it was a missing `index.js` that caused the issue: https://github.com/hotwired/hotwire-rails/issues/20#issuecomment-770203853.
