### ISSUE TITLE
Event to run javascript on turbo GET request which render frame 

### ISSUE THREAD

**Issue by parvesh-hyperiq** [hotwired/hotwire-rails#28]
I have link which get one modal box from backend and put into turbo frame with ID 'modal', In order to make it visible I need to run javascript `$('#editModal').modal()`, I was expecting after frame is rendered I will get hook on stimulus function `editStaff` But its not working

```
<%= link_to edit_staff_member_path(staff.id), class: "dropdown-item mainbody-text text-neutral-900 d-flex align-items-center", 'data-turbo-frame': 'modal', data: { controller: "account-profiles", action: :"turbo:visit->account-profiles#editStaff" } do %>
<i class="las la-pencil-alt font-size-24"></i><span class="ml-8">Edit</span>
<% end %>
```

I need help on this, either that's a issue or I am doing something wrong!!

**Comment by dhh** [comment]
Stimulus controllers are connected when they appear in the DOM. You can use the stimulus lifecycle hooks for this.
