### ISSUE TITLE
Update action redirects to 'show' route don't work

### ISSUE THREAD

**Issue by mvdmsoftware** [hotwired/hotwire-rails#29]
When redirecting to the 'show' route from the 'update' action, the redirect is not followed. I've noticed that this is always the case when the redirect goes to the same URL, but a different method.

In my case, the form submits a PUT request to `/books/1`, and the redirect is to the 'show' route which is also `/books/1`. The PUT request actually succeeds and the book is updated, but the redirect is not followed. Clicking the submit button of the form again does not trigger a second request.

The same happens when sending a POST to `/books` with a new book, and then redirecting back to the index, which is also routed to `/books`.

Is this intended behaviour in Turbo? If so, what is the convention for redirects from certain actions like 'create' and 'update'? What if I want to deviate from that? Are there any workarounds to make this work like I want it to?

Kind regards,
Michiel van der Meer

**Comment by dhh** [comment]
Can't recreate this on latest versions of Turbo using scaffolding. If you isolate the problem with a test case on latest, please reopen.
