### ISSUE TITLE
Failed on remove sprockets/railtie from the project

### ISSUE THREAD

**Issue by ismarsantos** [hotwired/hotwire-rails#30]
I was following [this guide](https://andycroll.com/ruby/turn-off-the-bits-of-rails-you-dont-use/) on how to remove some standard Rails components, when I removed the "sprockets/railtie" in favor of using "rails/webpacker" I get the following error message:

`method_missing ': undefined method' assets' for Rails Application Configuration`

Then I saw that the source of the error could be one of the dependencies on the gem "stimulus-rails" that is only compatible with asset pipeline, is there any way to use hotwire-rails only as a webpacker?

**Comment by yourtallness** [comment]
Same here, started a rails 6.1.3.1 / ruby 3 project without sprockets.

`hotwired-rails` will not install.

**Comment by aldent95** [comment]
Same here. Was using the Webpacker asset pipeline from the start with my current project (Rails 6.0) and updated a gem today that uses Hotwire and boom, website broken.
Having to stick to the non-hotwire version of that other gem for now until this is fixed.

**Comment by aldent95** [comment]
Issue seems to be in the Stimulus-rails subproject.
It was fixed in Turbo-rails in this PR https://github.com/hotwired/turbo-rails/pull/17 but not fixed in Stimulus-rails.
Ill look to open either a PR or an issue in Stimulus-rails to fix.

**Comment by aldent95** [comment]
Never mind, PR already open to fix it in stimulus-rails https://github.com/hotwired/stimulus-rails/pull/60

**Comment by jrcech** [comment]
Still not working. Generated a new Rails 6.1.3.2/Ruby 3.0.1 app with `-S` flag. Added hotwire-rails gem and neither `rails hotwire:install`, `rails turbo:install` and `rails stimulus:install` works.

**Comment by jrcech** [comment]
It's fixed. Just successfully installed hotwire with `rails hotwire:install` in a new generated app with `-S` flag. Thanks!
```
Using stimulus-rails 0.2.4
Using turbo-rails 0.5.10
Using hotwire-rails 0.1.3
```
