### ISSUE TITLE
Stimulus controller is not connected inside frames

### ISSUE THREAD

**Issue by AxelBriche** [hotwired/hotwire-rails#33]
Stimulus controllers are not connected when present inside a turbo-frame, the problem is know?

**Comment by seanpdoyle** [comment]
Is this a duplicate of https://github.com/hotwired/stimulus-rails/issues/56?

@AxelBriche could you share more details to help us reproduce the issue?

For instance, could you share a sample of the page's HTML and a sample of Stimulus controller's code?
