### ISSUE TITLE
Possibility to work with Hotwire without persisting information

### ISSUE THREAD

**Issue by murilomendes** [hotwired/hotwire-rails#44]
Hey guys! :) 

First of all. Congratulations. Hotwire is a very good tool for us. I just loved it. 

My case: 
I want to generate with web socks some informations in frontend. But, I don't to persist this data to show (yet). Is possible do it with Hotwire? Any suggestion by the way? 

Thank you very much. :)

**Comment by pinzonjulian** [comment]
Hey @murilomendes !
I think the repository's issue tracker is not the best place to ask this. 

Maybe try the official forum at https://discuss.hotwired.dev. 
Alternatively, join the StimulusReflex discord https://discord.gg/stimulus-reflex where there's a dedicated channel for all things Hotwire. 

Cheers!

**Comment by murilomendes** [comment]
Hey @pinzonjulian!

I'm so sorry! 
I'll create a post there. 

Thank you very much!
