### ISSUE TITLE
Error getting a simple example to work in Rails / Turbo / Hotwire

### ISSUE THREAD

**Issue by pitosalas** [hotwired/hotwire-rails#45]
Ruby 3.0.2 and Rails 6.1.4.1, from a fresh rails new, I edit Gemfile to add gem 'hotwire-rails', then bundle install, followed by rails Hotwire:install.

I get two errors: 

"You must import "./controllers" in your JavaScript entrypoint"
and
"You must import @hotwired/turbo-rails in your JavaScript entrypoint file"

Looking at the code it is checking for:

`if (Rails.root.join("app/javascript/application.js")).exist?`

But that file doesn't exist. What does exist is app/javascript/packs/application.js. Is this a bug?

If nothing else, please make the error message much more clear?

**Comment by dhh** [comment]
These checks are make in preparation for the new defaults in Rails 7. So those statements are not errors, but instructions, since the installer is now targeting Rails 7 defaults.

**Comment by pitosalas** [comment]
It should then say "warning" and not  be in red. It's a big red herring that I've been chasing in troubleshooting a tutorial of mine. So do I just ignore them in current rails? They are not needed?

Pito Salas
Faculty, Computer Science
Brandeis University

**Comment by dhh** [comment]
You need to follow the instructions. That is, that you must do the imports where you import your JS. It's just that with Rails 7, this will be done automatically through the installer 👍

**Comment by pitosalas** [comment]
Yes, but the instructions are wrong, at least from a new trier's (but experienced rails dev) perspective. The phrase "JavaScript entrypoint file" is a meaningless (and ungooglable) phrase - and in fact I still don't know where to put what new lines of code.

**Comment by Tarbetu** [comment]
As a newbie, it was really confusing. :)

I want to write the solutions for the newbies like me:
The "app/javascript/packs/application.js" is the entry point and "import '../controllers'" is the code which do you want to add, not "import './controllers'".

**Comment by dhh** [comment]
I could see us adding version specific instructions. Do take a stab at that in a PR if you like.

**Comment by pitosalas** [comment]
I added two PRs. My first ones ever, so be kind :)

Pito Salas
Faculty, Computer Science
Brandeis University
