### ISSUE TITLE
Gemfile.lock references invalid version of turbo-rails

### ISSUE THREAD

**Issue by philipithomas** [hotwired/hotwire-rails#46]
Looks like the Gemfile.lock references [turbo-rails](https://github.com/hotwired/turbo-rails/tags) using a versioning scheme that's been removed. 

People are reporting build errors related to this: https://stackoverflow.com/questions/69891921/rails-bundle-install-could-not-find-turbo-rails-7-1-1-in-any-of-the-sources

**Comment by dhh** [comment]
The Gemfile.lock associated with hotwire-rails is not referencing the yanked version. Seems like that might be coming from a bad mirror.
