### ISSUE TITLE
hotwire-rails, or turbo-rails, stimulus-rails

### ISSUE THREAD

**Issue by charlietag** [hotwired/hotwire-rails#47]
Hi hotwired Team ,

I found that ruby on rails 7 uses turbo-rails, stimulus-rails , not hotwire-rails.

Which way is preferred now ?
hotwire-rails , or turbo-rails + stimulus-rails

Thanks

**Comment by dhh** [comment]
hotwire-rails is just an aggregation of the dependency of those two other gems. Nothing in it by itself. Will probably just deprecate it. Not offering much value by itself.
