### ISSUE TITLE
Rails hotwire:install when using slim for layout file 

### ISSUE THREAD

**Issue by equivalent** [hotwired/hotwire-rails#6]
Given I'm using `slim-rails` 
And I have `app/views/application.html.slim` 
But no `app/views/application.html.erb` 
When I `rails hotwire:install`
Then  warning msg:

```
Thor::Error: The file /home/t/git/equivalent/sajtka/app/views/layouts/application.html.erb does not appear to exist
```

and

```
Default application.html.erb is missing!
        Add <%= stimulus_include_tags %> within the <head> tag in your custom layout.```
```

appears

```
Copying Stimulus JavaScript
      create  app/assets/javascripts
      create  app/assets/javascripts/controllers/hello_controller.js
      create  app/assets/javascripts/importmap.json.erb
      create  app/assets/javascripts/libraries
Add app/javascripts to asset pipeline manifest
      append  app/assets/config/manifest.js
Default application.html.erb is missing!
        Add <%= stimulus_include_tags %> within the <head> tag in your custom layout.
Turn off development debug mode
        gsub  config/environments/development.rb
Turn off rack-mini-profiler
        gsub  Gemfile
         run  bin/bundle from "."
```

My env:

```
hotwire-rails (0.1.2)
Ralls 6.0.3.2
```

**Comment by equivalent** [comment]
I think the warning msg is self explanatory and also what is the solution.

I just wanted to document this issue for future purposes.

**Comment by equivalent** [comment]
:thinking: now that I'm thinking about it this is more https://github.com/hotwired/turbo-rails issue. Should I close this one and create new one there ?

**Comment by dhh** [comment]
I'm not sure I understand the issue? If you're using something other than the default rendered, you can just add the stimulus_include_tags call manually. Or am I misunderstanding?

This message is coming from https://github.com/hotwired/stimulus-rails, btw.

**Comment by equivalent** [comment]
actually now I realized I'm overthinking it. My explanation is in https://github.com/hotwired/turbo-rails/pull/55  but you're right @dhh  `just add the stimulus_include_tags call manually.` 

closing this issue, thx for comment.

BTW I really love the idea of Hotwire <3 , Brilliant !
