### ISSUE TITLE
Auto unsubscribe from stream gives error

### ISSUE THREAD

**Issue by arpansac** [hotwired/hotwire-rails#7]
I have almost completed my project (to go live in 1 or 2 days) using Hotwired. It's amazing!
One thing that I noticed has been happening is whenever I navigate from a page which has `turbo_stream_from` to any other page (with or without the stream), it gives this error:

`Uncaught TypeError: this.subscription.unsubscribe is not a function`

Would be great if you can help find why this would be happening...

Thanks in advance!

**Comment by dhh** [comment]
This is fixed in turbo-rails 0.5.2 👍
