### ISSUE TITLE
XHR Responses causing problems with Devise

### ISSUE THREAD

**Issue by arpansac** [hotwired/hotwire-rails#9]
Coming from this: https://github.com/hotwired/turbo/pull/3
Is this functionality released on turbo-rails too in case of `form_for` ? I just updated the gem but probably this is yet to be launched.

Some more help needed (I'm at the verge of completing and launching my project, just fixing small things):
- When using `authenticate_user!` from devise, it constantly returns xhr response when the user isn't authenticated (if I override using https://github.com/heartcombo/devise/wiki/Redirect-to-new-registration-(sign-up)-path-if-unauthenticated, then it makes the sign-in form also malfunction because it redirects back to the sign-in without any notice/flash messages)

A Very Happy New Year Friends, you're doing a great job :)

**Comment by arpansac** [comment]
https://www.youtube.com/watch?v=yZDTBItc3ZM
This is a lifesaver for now!

**Comment by Nodalailama** [comment]
Hello,

May this help you: 
https://www.youtube.com/watch?v=yZDTBItc3ZM&list=UUIQmhQxCvLHRr3Beku77tww&ab_channel=GoRails

Cordialement,

**Comment by arpansac** [comment]
> Hello,
> 
> May this help you:
> https://www.youtube.com/watch?v=yZDTBItc3ZM&list=UUIQmhQxCvLHRr3Beku77tww&ab_channel=GoRails
> 
> Cordialement,

Hey, thank @Nodalailama, I tried it, but do you think that this should be the default behavior?

**Comment by arpansac** [comment]
> > Hello,
> > May this help you:
> > https://www.youtube.com/watch?v=yZDTBItc3ZM&list=UUIQmhQxCvLHRr3Beku77tww&ab_channel=GoRails
> > Cordialement,
> 
> Hey, thank @Nodalailama, I tried it, but do you think that this should be the default behavior?

Also, it works for the devise part, but when we are clicking a button inside a turboframe which need authenticate_user! it won't redirect... 

Is there a way we can intercept the incoming response and if it's for any of the devise paths then we redirect?

**Comment by marcelolx** [comment]
@arpansac Can you provide an example application to simulate the problem?
